//! TypeScript client code generator.
//!
//! Emits a typed TypeScript Prisma client from the schema IR. The generated
//! code imports `@prisma/client-runtime` (or equivalent) and provides
//! model delegates with full type safety.

use crate::error::CodegenError;
use crate::schema_ir::*;

/// Generates TypeScript client code from a schema IR.
pub struct TypeScriptGenerator;

impl TypeScriptGenerator {
    /// Generate the full TypeScript client source code.
    pub fn generate(ir: &SchemaIR) -> Result<String, CodegenError> {
        let mut out = String::new();

        out.push_str(&gen_header(ir));
        out.push_str(&gen_enums(ir));
        out.push_str(&gen_model_types(ir));
        out.push_str(&gen_input_types(ir));
        out.push_str(&gen_client_class(ir));

        Ok(out)
    }
}

fn gen_header(_ir: &SchemaIR) -> String {
    r#"// Generated by prisma-codegen. DO NOT EDIT.

import type { PrismaClient as BasePrismaClient } from '@prisma/client-runtime';

"#
    .to_string()
}

/// Escape a string for embedding in a TypeScript single-quoted string literal.
fn escape_ts_str(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('\'', "\\'")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
}

fn gen_enums(ir: &SchemaIR) -> String {
    let mut out = String::new();
    for e in &ir.enums {
        out.push_str(&format!("export const {} = {{\n", e.name));
        for v in &e.values {
            out.push_str(&format!("  {}: '{}',\n", v.name, escape_ts_str(&v.db_name)));
        }
        out.push_str("} as const;\n");
        out.push_str(&format!(
            "export type {} = (typeof {})[keyof typeof {}];\n\n",
            e.name, e.name, e.name
        ));
    }
    out
}

fn gen_model_types(ir: &SchemaIR) -> String {
    let mut out = String::new();
    out.push_str("// --- Model types ---\n\n");

    for model in &ir.models {
        out.push_str(&format!("export interface {} {{\n", model.name));
        for field in &model.fields {
            match field {
                ModelField::Scalar(sf) => {
                    let ts_type = scalar_to_ts_type(sf, ir);
                    let optional = if sf.arity == FieldArity::Optional {
                        " | null"
                    } else {
                        ""
                    };
                    if sf.arity == FieldArity::List {
                        out.push_str(&format!("  {}: {}[];\n", sf.name, ts_type));
                    } else {
                        out.push_str(&format!("  {}: {}{};\n", sf.name, ts_type, optional));
                    }
                }
                ModelField::Relation(_) => {
                    // Relations are not included in the base model type
                }
            }
        }
        out.push_str("}\n\n");
    }
    out
}

fn gen_input_types(ir: &SchemaIR) -> String {
    let mut out = String::new();
    out.push_str("// --- Input types ---\n\n");

    for model in &ir.models {
        // WhereInput
        out.push_str(&format!("export interface {}WhereInput {{\n", model.name));
        out.push_str(
            "  AND?: {}WhereInput | {}WhereInput[];\n"
                .replace("{}", &model.name)
                .as_str(),
        );
        out.push_str("  OR?: {}WhereInput[];\n".replace("{}", &model.name).as_str());
        out.push_str(
            "  NOT?: {}WhereInput | {}WhereInput[];\n"
                .replace("{}", &model.name)
                .as_str(),
        );
        for field in &model.fields {
            if let ModelField::Scalar(sf) = field {
                let filter_type = scalar_to_ts_filter_type(sf, ir);
                out.push_str(&format!("  {}?: {};\n", sf.name, filter_type));
            }
        }
        out.push_str("}\n\n");

        // WhereUniqueInput
        out.push_str(&format!("export interface {}WhereUniqueInput {{\n", model.name));
        for pk_field in &model.primary_key {
            if let Some(sf) = find_scalar_field(model, pk_field) {
                let ts_type = scalar_to_ts_type(sf, ir);
                out.push_str(&format!("  {}?: {};\n", sf.name, ts_type));
            }
        }
        for uc in &model.unique_constraints {
            for uc_field in uc {
                if let Some(sf) = find_scalar_field(model, uc_field) {
                    let ts_type = scalar_to_ts_type(sf, ir);
                    out.push_str(&format!("  {}?: {};\n", sf.name, ts_type));
                }
            }
        }
        out.push_str("}\n\n");

        // CreateInput
        out.push_str(&format!("export interface {}CreateInput {{\n", model.name));
        for field in &model.fields {
            if let ModelField::Scalar(sf) = field {
                if sf.is_autoincrement || sf.is_id {
                    continue;
                }
                let ts_type = scalar_to_ts_type(sf, ir);
                let optional = if sf.arity == FieldArity::Optional || sf.default.is_some() {
                    "?"
                } else {
                    ""
                };
                if sf.arity == FieldArity::List {
                    out.push_str(&format!("  {}{}:  {}[];\n", sf.name, optional, ts_type));
                } else {
                    let null_suffix = if sf.arity == FieldArity::Optional {
                        " | null"
                    } else {
                        ""
                    };
                    out.push_str(&format!("  {}{}: {}{};\n", sf.name, optional, ts_type, null_suffix));
                }
            }
        }
        out.push_str("}\n\n");

        // UpdateInput
        out.push_str(&format!("export interface {}UpdateInput {{\n", model.name));
        for field in &model.fields {
            if let ModelField::Scalar(sf) = field {
                if sf.is_id {
                    continue;
                }
                let ts_type = scalar_to_ts_type(sf, ir);
                let null_suffix = if sf.arity == FieldArity::Optional {
                    " | null"
                } else {
                    ""
                };
                out.push_str(&format!("  {}?: {}{};\n", sf.name, ts_type, null_suffix));
            }
        }
        out.push_str("}\n\n");

        // OrderByInput
        out.push_str(&format!("export interface {}OrderByInput {{\n", model.name));
        for field in &model.fields {
            if let ModelField::Scalar(sf) = field {
                out.push_str(&format!("  {}?: 'asc' | 'desc';\n", sf.name));
            }
        }
        out.push_str("}\n\n");

        // Select / Include
        out.push_str(&format!("export interface {}Select {{\n", model.name));
        for field in &model.fields {
            out.push_str(&format!("  {}?: boolean;\n", field.name()));
        }
        out.push_str("}\n\n");

        out.push_str(&format!("export interface {}Include {{\n", model.name));
        for field in &model.fields {
            if let ModelField::Relation(rf) = field {
                out.push_str(&format!(
                    "  {}?: boolean | {}FindManyArgs;\n",
                    rf.name, rf.related_model
                ));
            }
        }
        out.push_str("}\n\n");

        // FindManyArgs
        out.push_str(&format!("export interface {}FindManyArgs {{\n", model.name));
        out.push_str(&format!("  where?: {}WhereInput;\n", model.name));
        out.push_str(&format!(
            "  orderBy?: {}OrderByInput | {}OrderByInput[];\n",
            model.name, model.name
        ));
        out.push_str("  skip?: number;\n");
        out.push_str("  take?: number;\n");
        out.push_str(&format!("  cursor?: {}WhereUniqueInput;\n", model.name));
        out.push_str(&format!("  select?: {}Select;\n", model.name));
        out.push_str(&format!("  include?: {}Include;\n", model.name));
        out.push_str("}\n\n");
    }
    out
}

fn gen_client_class(ir: &SchemaIR) -> String {
    let mut out = String::new();
    out.push_str("// --- Client ---\n\n");
    out.push_str("export interface PrismaClient {\n");
    out.push_str("  $connect(): Promise<void>;\n");
    out.push_str("  $disconnect(): Promise<void>;\n");
    out.push_str("  $transaction<T>(fn: (tx: PrismaClient) => Promise<T>): Promise<T>;\n");
    out.push_str("  $queryRaw<T = unknown>(query: TemplateStringsArray, ...values: any[]): Promise<T>;\n");
    out.push_str("  $executeRaw(query: TemplateStringsArray, ...values: any[]): Promise<number>;\n\n");

    for model in &ir.models {
        let delegate_name = to_camel_case(&model.name);
        out.push_str(&format!("  {}: {}Delegate;\n", delegate_name, model.name));
    }
    out.push_str("}\n\n");

    // Model delegates
    for model in &ir.models {
        out.push_str(&format!("export interface {}Delegate {{\n", model.name));
        out.push_str(&format!(
            "  findMany(args?: {}FindManyArgs): Promise<{}[]>;\n",
            model.name, model.name
        ));
        out.push_str(&format!(
            "  findUnique(args: {{ where: {}WhereUniqueInput; select?: {}Select; include?: {}Include }}): Promise<{} | null>;\n",
            model.name, model.name, model.name, model.name
        ));
        out.push_str(&format!(
            "  findFirst(args?: {}FindManyArgs): Promise<{} | null>;\n",
            model.name, model.name
        ));
        out.push_str(&format!(
            "  findUniqueOrThrow(args: {{ where: {}WhereUniqueInput }}): Promise<{}>;\n",
            model.name, model.name
        ));
        out.push_str(&format!(
            "  findFirstOrThrow(args?: {}FindManyArgs): Promise<{}>;\n",
            model.name, model.name
        ));
        out.push_str(&format!(
            "  create(args: {{ data: {}CreateInput; select?: {}Select; include?: {}Include }}): Promise<{}>;\n",
            model.name, model.name, model.name, model.name
        ));
        out.push_str(&format!(
            "  update(args: {{ where: {}WhereUniqueInput; data: {}UpdateInput; select?: {}Select }}): Promise<{}>;\n",
            model.name, model.name, model.name, model.name
        ));
        out.push_str(&format!(
            "  delete(args: {{ where: {}WhereUniqueInput }}): Promise<{}>;\n",
            model.name, model.name
        ));
        out.push_str(&format!(
            "  updateMany(args: {{ where?: {}WhereInput; data: {}UpdateInput }}): Promise<{{ count: number }}>;\n",
            model.name, model.name
        ));
        out.push_str(&format!(
            "  deleteMany(args?: {{ where?: {}WhereInput }}): Promise<{{ count: number }}>;\n",
            model.name
        ));
        out.push_str(&format!(
            "  upsert(args: {{ where: {}WhereUniqueInput; create: {}CreateInput; update: {}UpdateInput }}): Promise<{}>;\n",
            model.name, model.name, model.name, model.name
        ));
        out.push_str(&format!(
            "  createMany(args: {{ data: {}CreateInput[] }}): Promise<{{ count: number }}>;\n",
            model.name
        ));
        out.push_str(&format!(
            "  createManyAndReturn(args: {{ data: {}CreateInput[] }}): Promise<{}[]>;\n",
            model.name, model.name
        ));
        out.push_str(&format!(
            "  updateManyAndReturn(args: {{ where?: {}WhereInput; data: {}UpdateInput }}): Promise<{}[]>;\n",
            model.name, model.name, model.name
        ));
        out.push_str(&format!(
            "  aggregate(args?: {{ where?: {}WhereInput }}): Promise<Aggregate{}>;\n",
            model.name, model.name
        ));
        out.push_str(&format!(
            "  groupBy(args: {{ where?: {}WhereInput; by: (keyof {})[] }}): Promise<{}GroupByOutput[]>;\n",
            model.name, model.name, model.name
        ));
        out.push_str(&format!(
            "  count(args?: {{ where?: {}WhereInput }}): Promise<number>;\n",
            model.name
        ));
        out.push_str("}\n\n");
    }
    out
}

fn scalar_to_ts_type(sf: &ScalarField, ir: &SchemaIR) -> String {
    match sf.scalar_kind {
        ScalarKind::Int | ScalarKind::BigInt => "number".to_string(),
        ScalarKind::Float | ScalarKind::Decimal => "number".to_string(),
        ScalarKind::String => "string".to_string(),
        ScalarKind::Boolean => "boolean".to_string(),
        ScalarKind::DateTime => "Date".to_string(),
        ScalarKind::Json => "JsonValue".to_string(),
        ScalarKind::Bytes => "Buffer".to_string(),
        ScalarKind::Uuid => "string".to_string(),
        ScalarKind::Enum(idx) => ir
            .enums
            .get(idx)
            .map(|e| e.name.clone())
            .unwrap_or_else(|| "string".to_string()),
        ScalarKind::Unsupported => "unknown".to_string(),
    }
}

fn scalar_to_ts_filter_type(sf: &ScalarField, ir: &SchemaIR) -> String {
    let base = scalar_to_ts_type(sf, ir);
    if sf.arity == FieldArity::Optional {
        format!("{base} | null | {base}Filter")
    } else {
        format!("{base} | {base}Filter")
    }
}

fn find_scalar_field<'a>(model: &'a ModelIR, name: &str) -> Option<&'a ScalarField> {
    model.fields.iter().find_map(|f| match f {
        ModelField::Scalar(sf) if sf.name == name => Some(sf),
        _ => None,
    })
}

fn to_camel_case(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_lowercase().to_string() + chars.as_str(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEST_SCHEMA: &str = r#"
        datasource db {
            provider = "postgresql"
        }

        model User {
            id    Int    @id @default(autoincrement())
            email String @unique
            name  String?
            posts Post[]
        }

        model Post {
            id       Int     @id @default(autoincrement())
            title    String
            published Boolean @default(false)
            authorId Int
            author   User    @relation(fields: [authorId], references: [id])
        }
    "#;

    #[test]
    fn generates_typescript() {
        let ir = SchemaIR::from_schema(TEST_SCHEMA).unwrap();
        let code = TypeScriptGenerator::generate(&ir).unwrap();

        assert!(code.contains("export interface User {"));
        assert!(code.contains("id: number;"));
        assert!(code.contains("email: string;"));
        assert!(code.contains("name: string | null;"));
    }

    #[test]
    fn generates_input_types() {
        let ir = SchemaIR::from_schema(TEST_SCHEMA).unwrap();
        let code = TypeScriptGenerator::generate(&ir).unwrap();

        assert!(code.contains("export interface UserWhereInput {"));
        assert!(code.contains("export interface UserCreateInput {"));
        assert!(code.contains("export interface UserUpdateInput {"));
        assert!(code.contains("export interface UserOrderByInput {"));
    }

    #[test]
    fn generates_client_interface() {
        let ir = SchemaIR::from_schema(TEST_SCHEMA).unwrap();
        let code = TypeScriptGenerator::generate(&ir).unwrap();

        assert!(code.contains("export interface PrismaClient {"));
        assert!(code.contains("user: UserDelegate;"));
        assert!(code.contains("post: PostDelegate;"));
    }

    #[test]
    fn generates_delegate_methods() {
        let ir = SchemaIR::from_schema(TEST_SCHEMA).unwrap();
        let code = TypeScriptGenerator::generate(&ir).unwrap();

        assert!(code.contains("export interface UserDelegate {"));
        assert!(code.contains("findMany(args?: UserFindManyArgs): Promise<User[]>;"));
        assert!(code.contains("create(args:"));
        assert!(code.contains("deleteMany(args?:"));
    }

    #[test]
    fn autoincrement_excluded_from_create_input() {
        let ir = SchemaIR::from_schema(TEST_SCHEMA).unwrap();
        let code = TypeScriptGenerator::generate(&ir).unwrap();

        // UserCreateInput should not have `id` since it's autoincrement
        let create_section = code
            .split("export interface UserCreateInput {")
            .nth(1)
            .unwrap()
            .split('}')
            .next()
            .unwrap();
        assert!(!create_section.contains("id:"), "id should not be in CreateInput");
        assert!(create_section.contains("email:"));
    }

    #[test]
    fn generates_enum_types() {
        let schema = r#"
            datasource db {
                provider = "postgresql"
            }

            enum Role {
                USER
                ADMIN
            }

            model User {
                id   Int  @id
                role Role
            }
        "#;

        let ir = SchemaIR::from_schema(schema).unwrap();
        let code = TypeScriptGenerator::generate(&ir).unwrap();

        assert!(code.contains("export const Role = {"));
        assert!(code.contains("USER: 'USER',"));
        assert!(code.contains("ADMIN: 'ADMIN',"));
        assert!(code.contains("export type Role = (typeof Role)[keyof typeof Role];"));
    }
}
