//! Rust client code generator.
//!
//! Emits typed Rust client code from the schema IR. The generated code
//! uses `prisma-client` as its runtime and provides compile-time validated
//! model access with strongly typed query builders.

use crate::error::CodegenError;
use crate::schema_ir::*;

/// Generates Rust client code from a schema IR.
pub struct RustGenerator;

impl RustGenerator {
    /// Generate the full Rust client source code.
    pub fn generate(ir: &SchemaIR) -> Result<String, CodegenError> {
        let mut out = String::new();

        out.push_str(&gen_header());
        out.push_str(&gen_enums(ir));
        out.push_str(&gen_model_structs(ir));
        out.push_str(&gen_input_structs(ir));
        out.push_str(&gen_delegates(ir));
        out.push_str(&gen_client(ir));

        Ok(out)
    }
}

fn gen_header() -> String {
    r#"// Generated by prisma-codegen. DO NOT EDIT.

#![allow(dead_code, unused_imports)]

use prisma_client::{
    ClientError, Operation, PrismaClient as BasePrismaClient, QueryBuilder, Selection,
};
use serde::{Deserialize, Serialize};
use serde_json::Value;

"#
    .to_string()
}

/// Escape a string for embedding in a Rust double-quoted string literal.
fn escape_rust_str(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

fn gen_enums(ir: &SchemaIR) -> String {
    let mut out = String::new();
    for e in &ir.enums {
        out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n");
        out.push_str(&format!("pub enum {} {{\n", e.name));
        for v in &e.values {
            if v.name != v.db_name {
                out.push_str(&format!("    #[serde(rename = \"{}\")]\n", escape_rust_str(&v.db_name)));
            }
            out.push_str(&format!("    {},\n", v.name));
        }
        out.push_str("}\n\n");

        // Display impl for serialization to query args
        out.push_str(&format!("impl std::fmt::Display for {} {{\n", e.name));
        out.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
        out.push_str("        match self {\n");
        for v in &e.values {
            out.push_str(&format!(
                "            {}::{} => write!(f, \"{}\"),\n",
                e.name,
                v.name,
                escape_rust_str(&v.db_name)
            ));
        }
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }
    out
}

fn gen_model_structs(ir: &SchemaIR) -> String {
    let mut out = String::new();
    out.push_str("// --- Model structs ---\n\n");

    for model in &ir.models {
        // The Prisma engine returns camelCase field names in JSON responses.
        // Generated Rust structs use snake_case field names, so we need
        // rename_all = "camelCase" to deserialize correctly.
        out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        out.push_str("#[serde(rename_all = \"camelCase\")]\n");
        out.push_str(&format!("pub struct {} {{\n", model.name));
        for field in &model.fields {
            if let ModelField::Scalar(sf) = field {
                let rust_type = scalar_to_rust_type(sf, ir);
                let full_type = match sf.arity {
                    FieldArity::Required => rust_type,
                    FieldArity::Optional => format!("Option<{}>", rust_type),
                    FieldArity::List => format!("Vec<{}>", rust_type),
                };
                if sf.name != sf.db_name {
                    out.push_str(&format!(
                        "    #[serde(rename = \"{}\")]\n",
                        escape_rust_str(&sf.db_name)
                    ));
                }
                out.push_str(&format!("    pub {}: {},\n", to_snake_case(&sf.name), full_type));
            }
        }
        out.push_str("}\n\n");

        // Model with relations
        out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        out.push_str("#[serde(rename_all = \"camelCase\")]\n");
        out.push_str(&format!("pub struct {}WithRelations {{\n", model.name));
        out.push_str("    #[serde(flatten)]\n");
        out.push_str(&format!("    pub base: {},\n", model.name));
        for field in &model.fields {
            if let ModelField::Relation(rf) = field {
                let rel_type = match rf.arity {
                    FieldArity::Required => rf.related_model.clone(),
                    FieldArity::Optional => format!("Option<{}>", rf.related_model),
                    FieldArity::List => format!("Vec<{}>", rf.related_model),
                };
                out.push_str(&format!("    pub {}: {},\n", to_snake_case(&rf.name), rel_type));
            }
        }
        out.push_str("}\n\n");
    }
    out
}

fn gen_input_structs(ir: &SchemaIR) -> String {
    let mut out = String::new();
    out.push_str("// --- Input types ---\n\n");

    for model in &ir.models {
        // CreateInput
        out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        out.push_str("#[serde(rename_all = \"camelCase\")]\n");
        out.push_str(&format!("pub struct {}CreateInput {{\n", model.name));
        for field in &model.fields {
            if let ModelField::Scalar(sf) = field {
                if sf.is_autoincrement || sf.is_id {
                    continue;
                }
                let rust_type = scalar_to_rust_type(sf, ir);
                let (full_type, serde_attr) = if sf.arity == FieldArity::Optional || sf.default.is_some() {
                    (
                        format!("Option<{}>", rust_type),
                        "    #[serde(skip_serializing_if = \"Option::is_none\")]\n".to_string(),
                    )
                } else if sf.arity == FieldArity::List {
                    (format!("Vec<{}>", rust_type), String::new())
                } else {
                    (rust_type, String::new())
                };
                out.push_str(&serde_attr);
                out.push_str(&format!("    pub {}: {},\n", to_snake_case(&sf.name), full_type));
            }
        }
        out.push_str("}\n\n");

        // UpdateInput
        out.push_str("#[derive(Debug, Clone, Default, Serialize, Deserialize)]\n");
        out.push_str("#[serde(rename_all = \"camelCase\")]\n");
        out.push_str(&format!("pub struct {}UpdateInput {{\n", model.name));
        for field in &model.fields {
            if let ModelField::Scalar(sf) = field {
                if sf.is_id {
                    continue;
                }
                let rust_type = scalar_to_rust_type(sf, ir);
                out.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
                out.push_str(&format!(
                    "    pub {}: Option<{}>,\n",
                    to_snake_case(&sf.name),
                    rust_type
                ));
            }
        }
        out.push_str("}\n\n");
    }
    out
}

fn gen_delegates(ir: &SchemaIR) -> String {
    let mut out = String::new();
    out.push_str("// --- Model delegates ---\n\n");

    for model in &ir.models {
        out.push_str(&format!(
            "pub struct {}Delegate<'a> {{\n    client: &'a BasePrismaClient,\n}}\n\n",
            model.name
        ));

        out.push_str(&format!("impl<'a> {}Delegate<'a> {{\n", model.name));

        // findMany
        out.push_str(&format!(
            r#"    pub async fn find_many(&self) -> Result<Vec<{name}>, ClientError> {{
        let qb = QueryBuilder::new("{name}", Operation::FindMany);
        let result = self.client.execute(&qb).await?;
        let items: Vec<{name}> = serde_json::from_value(result)?;
        Ok(items)
    }}

"#,
            name = model.name
        ));

        // findUnique
        out.push_str(&format!(
            r#"    pub async fn find_unique(&self, r#where: Value) -> Result<Option<{name}>, ClientError> {{
        let qb = QueryBuilder::new("{name}", Operation::FindUnique)
            .where_arg(r#where);
        let result = self.client.execute(&qb).await?;
        if result.is_null() {{
            return Ok(None);
        }}
        let item: {name} = serde_json::from_value(result)?;
        Ok(Some(item))
    }}

"#,
            name = model.name
        ));

        // findFirst
        out.push_str(&format!(
            r#"    pub async fn find_first(&self) -> Result<Option<{name}>, ClientError> {{
        let qb = QueryBuilder::new("{name}", Operation::FindFirst);
        let result = self.client.execute(&qb).await?;
        if result.is_null() {{
            return Ok(None);
        }}
        let item: {name} = serde_json::from_value(result)?;
        Ok(Some(item))
    }}

"#,
            name = model.name
        ));

        // findUniqueOrThrow
        out.push_str(&format!(
            r#"    pub async fn find_unique_or_throw(&self, r#where: Value) -> Result<{name}, ClientError> {{
        let qb = QueryBuilder::new("{name}", Operation::FindUniqueOrThrow)
            .where_arg(r#where);
        let result = self.client.execute(&qb).await?;
        let item: {name} = serde_json::from_value(result)?;
        Ok(item)
    }}

"#,
            name = model.name
        ));

        // findFirstOrThrow
        out.push_str(&format!(
            r#"    pub async fn find_first_or_throw(&self) -> Result<{name}, ClientError> {{
        let qb = QueryBuilder::new("{name}", Operation::FindFirstOrThrow);
        let result = self.client.execute(&qb).await?;
        let item: {name} = serde_json::from_value(result)?;
        Ok(item)
    }}

"#,
            name = model.name
        ));

        // create
        out.push_str(&format!(
            r#"    pub async fn create(&self, data: {name}CreateInput) -> Result<{name}, ClientError> {{
        let data_json = serde_json::to_value(&data)?;
        let qb = QueryBuilder::new("{name}", Operation::CreateOne)
            .data(data_json);
        let result = self.client.execute(&qb).await?;
        let item: {name} = serde_json::from_value(result)?;
        Ok(item)
    }}

"#,
            name = model.name
        ));

        // update
        out.push_str(&format!(
            r#"    pub async fn update(&self, r#where: Value, data: {name}UpdateInput) -> Result<{name}, ClientError> {{
        let data_json = serde_json::to_value(&data)?;
        let qb = QueryBuilder::new("{name}", Operation::UpdateOne)
            .where_arg(r#where)
            .data(data_json);
        let result = self.client.execute(&qb).await?;
        let item: {name} = serde_json::from_value(result)?;
        Ok(item)
    }}

"#,
            name = model.name
        ));

        // createMany
        out.push_str(&format!(
            r#"    pub async fn create_many(&self, data: Vec<{name}CreateInput>) -> Result<i64, ClientError> {{
        let data_json = serde_json::to_value(&data)?;
        let qb = QueryBuilder::new("{name}", Operation::CreateMany)
            .data(data_json)
            .selection(Selection::select().field("count"));
        let result = self.client.execute(&qb).await?;
        let count = result["count"].as_i64().unwrap_or(0);
        Ok(count)
    }}

"#,
            name = model.name
        ));

        // upsert
        out.push_str(&format!(
            r#"    pub async fn upsert(&self, r#where: Value, create: {name}CreateInput, update: {name}UpdateInput) -> Result<{name}, ClientError> {{
        let create_json = serde_json::to_value(&create)?;
        let update_json = serde_json::to_value(&update)?;
        let qb = QueryBuilder::new("{name}", Operation::UpsertOne)
            .where_arg(r#where)
            .arg("create", create_json)
            .arg("update", update_json);
        let result = self.client.execute(&qb).await?;
        let item: {name} = serde_json::from_value(result)?;
        Ok(item)
    }}

"#,
            name = model.name
        ));

        // delete
        out.push_str(&format!(
            r#"    pub async fn delete(&self, r#where: Value) -> Result<{name}, ClientError> {{
        let qb = QueryBuilder::new("{name}", Operation::DeleteOne)
            .where_arg(r#where);
        let result = self.client.execute(&qb).await?;
        let item: {name} = serde_json::from_value(result)?;
        Ok(item)
    }}

"#,
            name = model.name
        ));

        // deleteMany
        out.push_str(&format!(
            r#"    pub async fn delete_many(&self, r#where: Option<Value>) -> Result<i64, ClientError> {{
        let mut qb = QueryBuilder::new("{name}", Operation::DeleteMany)
            .selection(Selection::select().field("count"));
        if let Some(w) = r#where {{
            qb = qb.where_arg(w);
        }}
        let result = self.client.execute(&qb).await?;
        let count = result["count"].as_i64().unwrap_or(0);
        Ok(count)
    }}

"#,
            name = model.name
        ));

        // updateMany
        out.push_str(&format!(
            r#"    pub async fn update_many(&self, r#where: Option<Value>, data: {name}UpdateInput) -> Result<i64, ClientError> {{
        let data_json = serde_json::to_value(&data)?;
        let mut qb = QueryBuilder::new("{name}", Operation::UpdateMany)
            .data(data_json)
            .selection(Selection::select().field("count"));
        if let Some(w) = r#where {{
            qb = qb.where_arg(w);
        }}
        let result = self.client.execute(&qb).await?;
        let count = result["count"].as_i64().unwrap_or(0);
        Ok(count)
    }}

"#,
            name = model.name
        ));

        // count
        out.push_str(&format!(
            r#"    pub async fn count(&self, r#where: Option<Value>) -> Result<i64, ClientError> {{
        let mut qb = QueryBuilder::new("{name}", Operation::Aggregate)
            .selection(Selection::select().field("_count"));
        if let Some(w) = r#where {{
            qb = qb.where_arg(w);
        }}
        let result = self.client.execute(&qb).await?;
        let count = result["_count"]["_all"].as_i64().unwrap_or(0);
        Ok(count)
    }}

"#,
            name = model.name
        ));

        // aggregate
        out.push_str(&format!(
            r#"    pub async fn aggregate(&self, r#where: Option<Value>) -> Result<Value, ClientError> {{
        let mut qb = QueryBuilder::new("{name}", Operation::Aggregate);
        if let Some(w) = r#where {{
            qb = qb.where_arg(w);
        }}
        let result = self.client.execute(&qb).await?;
        Ok(result)
    }}

"#,
            name = model.name
        ));

        // groupBy
        out.push_str(&format!(
            r#"    pub async fn group_by(&self, by: Vec<String>, r#where: Option<Value>) -> Result<Value, ClientError> {{
        let by_json: Vec<Value> = by.into_iter().map(Value::String).collect();
        let mut qb = QueryBuilder::new("{name}", Operation::GroupBy)
            .arg("by", Value::Array(by_json));
        if let Some(w) = r#where {{
            qb = qb.where_arg(w);
        }}
        let result = self.client.execute(&qb).await?;
        Ok(result)
    }}

"#,
            name = model.name
        ));

        out.push_str("}\n\n");
    }
    out
}

fn gen_client(ir: &SchemaIR) -> String {
    let mut out = String::new();
    out.push_str("// --- Generated PrismaClient ---\n\n");
    out.push_str("pub struct PrismaClient {\n");
    out.push_str("    inner: BasePrismaClient,\n");
    out.push_str("}\n\n");

    out.push_str("impl PrismaClient {\n");
    out.push_str("    pub fn new(inner: BasePrismaClient) -> Self {\n");
    out.push_str("        Self { inner }\n");
    out.push_str("    }\n\n");

    for model in &ir.models {
        let snake = to_snake_case(&model.name);
        out.push_str(&format!(
            "    pub fn {}(&self) -> {}Delegate<'_> {{\n",
            snake, model.name
        ));
        out.push_str(&format!("        {}Delegate {{ client: &self.inner }}\n", model.name));
        out.push_str("    }\n\n");
    }

    out.push_str("    pub async fn disconnect(self) -> Result<(), ClientError> {\n");
    out.push_str("        self.inner.disconnect().await\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn scalar_to_rust_type(sf: &ScalarField, ir: &SchemaIR) -> String {
    match sf.scalar_kind {
        ScalarKind::Int => "i32".to_string(),
        ScalarKind::BigInt => "i64".to_string(),
        ScalarKind::Float | ScalarKind::Decimal => "f64".to_string(),
        ScalarKind::String | ScalarKind::Uuid => "String".to_string(),
        ScalarKind::Boolean => "bool".to_string(),
        ScalarKind::DateTime => "String".to_string(),
        ScalarKind::Json => "Value".to_string(),
        ScalarKind::Bytes => "Vec<u8>".to_string(),
        ScalarKind::Enum(idx) => ir
            .enums
            .get(idx)
            .map(|e| e.name.clone())
            .unwrap_or_else(|| "String".to_string()),
        ScalarKind::Unsupported => "Value".to_string(),
    }
}

fn to_snake_case(name: &str) -> String {
    let mut result = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(ch.to_lowercase().next().unwrap_or(ch));
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEST_SCHEMA: &str = r#"
        datasource db {
            provider = "postgresql"
        }

        model User {
            id    Int    @id @default(autoincrement())
            email String @unique
            name  String?
            posts Post[]
        }

        model Post {
            id       Int     @id @default(autoincrement())
            title    String
            published Boolean @default(false)
            authorId Int
            author   User    @relation(fields: [authorId], references: [id])
        }
    "#;

    #[test]
    fn generates_rust_code() {
        let ir = SchemaIR::from_schema(TEST_SCHEMA).unwrap();
        let code = RustGenerator::generate(&ir).unwrap();

        assert!(code.contains("pub struct User {"));
        assert!(code.contains("pub id: i32,"));
        assert!(code.contains("pub email: String,"));
        assert!(code.contains("pub name: Option<String>,"));
    }

    #[test]
    fn generates_create_input() {
        let ir = SchemaIR::from_schema(TEST_SCHEMA).unwrap();
        let code = RustGenerator::generate(&ir).unwrap();

        assert!(code.contains("pub struct UserCreateInput {"));
        // id should be excluded (autoincrement)
        let create_section = code
            .split("pub struct UserCreateInput {")
            .nth(1)
            .unwrap()
            .split('}')
            .next()
            .unwrap();
        assert!(!create_section.contains("id:"));
        assert!(create_section.contains("pub email: String,"));
    }

    #[test]
    fn generates_update_input() {
        let ir = SchemaIR::from_schema(TEST_SCHEMA).unwrap();
        let code = RustGenerator::generate(&ir).unwrap();

        assert!(code.contains("pub struct UserUpdateInput {"));
        assert!(code.contains("pub email: Option<String>,"));
    }

    #[test]
    fn generates_delegates() {
        let ir = SchemaIR::from_schema(TEST_SCHEMA).unwrap();
        let code = RustGenerator::generate(&ir).unwrap();

        assert!(code.contains("pub struct UserDelegate<'a>"));
        assert!(code.contains("pub async fn find_many("));
        assert!(code.contains("pub async fn find_unique("));
        assert!(code.contains("pub async fn create("));
        assert!(code.contains("pub async fn delete_many("));
    }

    #[test]
    fn generates_client() {
        let ir = SchemaIR::from_schema(TEST_SCHEMA).unwrap();
        let code = RustGenerator::generate(&ir).unwrap();

        assert!(code.contains("pub struct PrismaClient {"));
        assert!(code.contains("pub fn user(&self) -> UserDelegate<'_>"));
        assert!(code.contains("pub fn post(&self) -> PostDelegate<'_>"));
    }

    #[test]
    fn generates_with_relations_struct() {
        let ir = SchemaIR::from_schema(TEST_SCHEMA).unwrap();
        let code = RustGenerator::generate(&ir).unwrap();

        assert!(code.contains("pub struct UserWithRelations {"));
        assert!(code.contains("pub posts: Vec<Post>,"));
    }

    #[test]
    fn generates_enum_types() {
        let schema = r#"
            datasource db {
                provider = "postgresql"
            }

            enum Role {
                USER
                ADMIN
            }

            model User {
                id   Int  @id
                role Role
            }
        "#;

        let ir = SchemaIR::from_schema(schema).unwrap();
        let code = RustGenerator::generate(&ir).unwrap();

        assert!(code.contains("pub enum Role {"));
        assert!(code.contains("    USER,"));
        assert!(code.contains("    ADMIN,"));
        assert!(code.contains("impl std::fmt::Display for Role {"));
    }

    #[test]
    fn snake_case_conversion() {
        assert_eq!(to_snake_case("User"), "user");
        assert_eq!(to_snake_case("Post"), "post");
        assert_eq!(to_snake_case("UserProfile"), "user_profile");
        assert_eq!(to_snake_case("authorId"), "author_id");
    }

    #[test]
    fn generated_structs_have_camelcase_serde() {
        let ir = SchemaIR::from_schema(TEST_SCHEMA).unwrap();
        let code = RustGenerator::generate(&ir).unwrap();

        // Model structs must have rename_all = "camelCase" for Prisma engine compatibility
        assert!(
            code.contains("#[serde(rename_all = \"camelCase\")]\npub struct User {"),
            "User struct missing rename_all = camelCase"
        );
        assert!(
            code.contains("#[serde(rename_all = \"camelCase\")]\npub struct Post {"),
            "Post struct missing rename_all = camelCase"
        );

        // WithRelations structs
        assert!(
            code.contains("#[serde(rename_all = \"camelCase\")]\npub struct UserWithRelations {"),
            "UserWithRelations struct missing rename_all = camelCase"
        );

        // Input structs
        assert!(
            code.contains("#[serde(rename_all = \"camelCase\")]\npub struct UserCreateInput {"),
            "UserCreateInput struct missing rename_all = camelCase"
        );
        assert!(
            code.contains("#[serde(rename_all = \"camelCase\")]\npub struct UserUpdateInput {"),
            "UserUpdateInput struct missing rename_all = camelCase"
        );
    }
}
