//! Golden (snapshot) tests for query compilation across providers.
//!
//! Uses `insta` to capture and verify the SQL generated by the query compiler
//! for each database provider. Run `cargo insta review` to update snapshots.

use prisma_cross_compat::{compile_operation, compiler_for_provider, extract_sql_queries};

const SCHEMA_TEMPLATE: &str = r#"
    datasource db {
        provider = "{provider}"
    }

    model User {
        id    Int    @id @default(autoincrement())
        email String @unique
        name  String?
        posts Post[]
    }

    model Post {
        id        Int    @id @default(autoincrement())
        title     String
        content   String?
        published Boolean @default(false)
        authorId  Int
        author    User   @relation(fields: [authorId], references: [id])
    }
"#;

fn schema_for(provider: &str) -> String {
    SCHEMA_TEMPLATE.replace("{provider}", provider)
}

fn compile_sql(provider: &str, request: &str) -> Vec<String> {
    let schema = schema_for(provider);
    let compiler = compiler_for_provider(provider, &schema);
    let plan = compile_operation(&compiler, request).unwrap_or_else(|e| panic!("{provider}: {e}"));
    extract_sql_queries(&plan)
}

// -- findMany --

#[test]
fn golden_find_many_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "User",
        "action": "findMany",
        "query": { "selection": { "$scalars": true } }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_find_many_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "User",
        "action": "findMany",
        "query": { "selection": { "$scalars": true } }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_find_many_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "User",
        "action": "findMany",
        "query": { "selection": { "$scalars": true } }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

// -- findUnique --

#[test]
fn golden_find_unique_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "User",
        "action": "findUnique",
        "query": {
            "arguments": { "where": { "id": 1 } },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_find_unique_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "User",
        "action": "findUnique",
        "query": {
            "arguments": { "where": { "id": 1 } },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_find_unique_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "User",
        "action": "findUnique",
        "query": {
            "arguments": { "where": { "id": 1 } },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

// -- createOne --

#[test]
fn golden_create_one_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "User",
        "action": "createOne",
        "query": {
            "arguments": {
                "data": { "email": "test@example.com", "name": "Test" }
            },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_create_one_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "User",
        "action": "createOne",
        "query": {
            "arguments": {
                "data": { "email": "test@example.com", "name": "Test" }
            },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_create_one_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "User",
        "action": "createOne",
        "query": {
            "arguments": {
                "data": { "email": "test@example.com", "name": "Test" }
            },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

// -- updateMany --

#[test]
fn golden_update_many_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "User",
        "action": "updateMany",
        "query": {
            "arguments": {
                "where": { "name": "Test" },
                "data": { "name": "Updated" }
            },
            "selection": { "count": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_update_many_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "User",
        "action": "updateMany",
        "query": {
            "arguments": {
                "where": { "name": "Test" },
                "data": { "name": "Updated" }
            },
            "selection": { "count": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_update_many_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "User",
        "action": "updateMany",
        "query": {
            "arguments": {
                "where": { "name": "Test" },
                "data": { "name": "Updated" }
            },
            "selection": { "count": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

// -- deleteMany --

#[test]
fn golden_delete_many_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "Post",
        "action": "deleteMany",
        "query": {
            "arguments": { "where": { "published": false } },
            "selection": { "count": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_delete_many_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "Post",
        "action": "deleteMany",
        "query": {
            "arguments": { "where": { "published": false } },
            "selection": { "count": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_delete_many_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "Post",
        "action": "deleteMany",
        "query": {
            "arguments": { "where": { "published": false } },
            "selection": { "count": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

// -- findMany with relation --

#[test]
fn golden_find_many_with_relation_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "User",
        "action": "findMany",
        "query": {
            "selection": {
                "$scalars": true,
                "posts": {
                    "selection": { "$scalars": true }
                }
            }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_find_many_with_relation_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "User",
        "action": "findMany",
        "query": {
            "selection": {
                "$scalars": true,
                "posts": {
                    "selection": { "$scalars": true }
                }
            }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_find_many_with_relation_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "User",
        "action": "findMany",
        "query": {
            "selection": {
                "$scalars": true,
                "posts": {
                    "selection": { "$scalars": true }
                }
            }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

// -- findFirst --

#[test]
fn golden_find_first_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "User",
        "action": "findFirst",
        "query": {
            "arguments": { "where": { "name": "Test" } },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_find_first_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "User",
        "action": "findFirst",
        "query": {
            "arguments": { "where": { "name": "Test" } },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_find_first_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "User",
        "action": "findFirst",
        "query": {
            "arguments": { "where": { "name": "Test" } },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

// -- deleteOne --

#[test]
fn golden_delete_one_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "User",
        "action": "deleteOne",
        "query": {
            "arguments": { "where": { "id": 1 } },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_delete_one_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "User",
        "action": "deleteOne",
        "query": {
            "arguments": { "where": { "id": 1 } },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_delete_one_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "User",
        "action": "deleteOne",
        "query": {
            "arguments": { "where": { "id": 1 } },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

// -- updateOne --

#[test]
fn golden_update_one_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "User",
        "action": "updateOne",
        "query": {
            "arguments": {
                "where": { "id": 1 },
                "data": { "name": "Updated" }
            },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_update_one_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "User",
        "action": "updateOne",
        "query": {
            "arguments": {
                "where": { "id": 1 },
                "data": { "name": "Updated" }
            },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_update_one_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "User",
        "action": "updateOne",
        "query": {
            "arguments": {
                "where": { "id": 1 },
                "data": { "name": "Updated" }
            },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

// -- upsertOne --

#[test]
fn golden_upsert_one_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "User",
        "action": "upsertOne",
        "query": {
            "arguments": {
                "where": { "email": "test@example.com" },
                "create": { "email": "test@example.com", "name": "New" },
                "update": { "name": "Existing" }
            },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_upsert_one_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "User",
        "action": "upsertOne",
        "query": {
            "arguments": {
                "where": { "email": "test@example.com" },
                "create": { "email": "test@example.com", "name": "New" },
                "update": { "name": "Existing" }
            },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_upsert_one_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "User",
        "action": "upsertOne",
        "query": {
            "arguments": {
                "where": { "email": "test@example.com" },
                "create": { "email": "test@example.com", "name": "New" },
                "update": { "name": "Existing" }
            },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

// -- createMany --

#[test]
fn golden_create_many_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "User",
        "action": "createMany",
        "query": {
            "arguments": {
                "data": [
                    { "email": "a@example.com", "name": "A" },
                    { "email": "b@example.com", "name": "B" }
                ]
            },
            "selection": { "count": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_create_many_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "User",
        "action": "createMany",
        "query": {
            "arguments": {
                "data": [
                    { "email": "a@example.com", "name": "A" },
                    { "email": "b@example.com", "name": "B" }
                ]
            },
            "selection": { "count": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_create_many_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "User",
        "action": "createMany",
        "query": {
            "arguments": {
                "data": [
                    { "email": "a@example.com", "name": "A" },
                    { "email": "b@example.com", "name": "B" }
                ]
            },
            "selection": { "count": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

// -- aggregate --

#[test]
fn golden_aggregate_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "User",
        "action": "aggregate",
        "query": {
            "selection": {
                "_count": { "selection": { "_all": true } },
                "_min": { "selection": { "id": true } },
                "_max": { "selection": { "id": true } }
            }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_aggregate_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "User",
        "action": "aggregate",
        "query": {
            "selection": {
                "_count": { "selection": { "_all": true } },
                "_min": { "selection": { "id": true } },
                "_max": { "selection": { "id": true } }
            }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_aggregate_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "User",
        "action": "aggregate",
        "query": {
            "selection": {
                "_count": { "selection": { "_all": true } },
                "_min": { "selection": { "id": true } },
                "_max": { "selection": { "id": true } }
            }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

// -- groupBy --

#[test]
fn golden_group_by_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "User",
        "action": "groupBy",
        "query": {
            "arguments": { "by": ["name"] },
            "selection": {
                "name": true,
                "_count": { "selection": { "_all": true } }
            }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_group_by_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "User",
        "action": "groupBy",
        "query": {
            "arguments": { "by": ["name"] },
            "selection": {
                "name": true,
                "_count": { "selection": { "_all": true } }
            }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_group_by_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "User",
        "action": "groupBy",
        "query": {
            "arguments": { "by": ["name"] },
            "selection": {
                "name": true,
                "_count": { "selection": { "_all": true } }
            }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

// -- findMany with orderBy --

#[test]
fn golden_find_many_order_by_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "User",
        "action": "findMany",
        "query": {
            "arguments": { "orderBy": [{ "email": "desc" }] },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_find_many_order_by_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "User",
        "action": "findMany",
        "query": {
            "arguments": { "orderBy": [{ "email": "desc" }] },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_find_many_order_by_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "User",
        "action": "findMany",
        "query": {
            "arguments": { "orderBy": [{ "email": "desc" }] },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

// -- findMany with skip/take --

#[test]
fn golden_find_many_pagination_pg() {
    let sqls = compile_sql(
        "postgresql",
        r#"{
        "modelName": "User",
        "action": "findMany",
        "query": {
            "arguments": { "skip": 5, "take": 10 },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_find_many_pagination_mysql() {
    let sqls = compile_sql(
        "mysql",
        r#"{
        "modelName": "User",
        "action": "findMany",
        "query": {
            "arguments": { "skip": 5, "take": 10 },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}

#[test]
fn golden_find_many_pagination_sqlite() {
    let sqls = compile_sql(
        "sqlite",
        r#"{
        "modelName": "User",
        "action": "findMany",
        "query": {
            "arguments": { "skip": 5, "take": 10 },
            "selection": { "$scalars": true }
        }
    }"#,
    );
    insta::assert_json_snapshot!(sqls);
}
